server:
  port: 8080

logging:
  config: classpath:logback-spring.xml
  path: log
#  level:
#    org.springframework.boot.autoconfigure: ERROR

spring:
  application:
    name: spring-core-dome
  datasource:
    type: com.alibaba.druid.pool.xa.DruidXADataSource
    druid:
      base:
        name: base
        username: root
        password: 123456
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: 'jdbc:mysql://localhost:3306/base?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&'
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: true
        testOnReturn: true
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
      order:
        name: order
        username: zcc
        password: 123456
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: 'jdbc:mysql://192.168.1.7:3306/order?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&'
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: true
        testOnReturn: true
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20

  jta:
    atomikos:
      properties:
        service: com.atomikos.icatch.standalone.UserTransactionServiceFactory
        max_timeout: 600000
        default_jta_timeout: 600000
        log_base_dir: transaction-logs
        log_base_name: springboot-mybatis
        serial_jta_transactions: false
#    log-dir: classpath:tx-logs
#    transaction-manager-id: txManager

  resources:
    static-locations: 'classpath:/static/'
    cache:
      cachecontrol:
        max-age: 10s
    #        no-cache: false
    #        s-max-age: 20

  mvc:
    view:
      prefix: '/resources/templates/'
      suffix: '.html'
    static-path-pattern: '/static/**'

  #redis配置开始
  # Redis数据库索引（默认为0）
  redis:
    database: 0
    # Redis服务器地址
#    host: 192.168.1.7
    # Redis服务器连接端口
#    port: 6379
    # Redis服务器连接密码（默认为空）
#    password: 123456
    # 连接池最大连接数（使用负值表示没有限制）
    jedispool:
      max-active: 1024
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: 10000
      # 连接池中的最大空闲连接
      max-idle: 200
      # 连接池中的最小空闲连接
      min-idle: 0
    # 连接超时时间（毫秒）
    timeout: 10000
    #节点
    cluster:
      nodes: 192.168.1.7:6381,192.168.1.7:6382,192.168.1.7:6383,192.168.1.7:6384,192.168.1.7:6385,192.168.1.7:6386
    #redis配置结束
    block-when-exhausted: true

  cache:
    type: redis
    redis:
      time-to-live: 10000
      cache-null-values: false
#      keyPrefix: ""
#      useKeyPrefix: true

mybatis:
#  mapper-locations: classpath*:mapping/**/*.xml
#  typeAliasesPackage: com.ytt.springcoredemo.model
  type-handlers-package: com.ytt.springcoredemo.dao.handler
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    useGeneratedKeys: true

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
#  security:
#    enabled: false

info:
  blog-url: http://www.ytt.com
  author: enjoy
  version: v1.0.1



